import 'Classes.dart';
List<Question> questionBank = [
  Question('The Earth is flat.', false),
  Question('Water boils at 100 degrees Celsius at sea level.', true),
  Question('The Sun is a planet.', false),
  Question('Oxygen is the most abundant element in Earth\'s atmosphere.', false),
  Question('All mammals lay eggs.', false),
  Question('Pluto is considered a planet in our solar system.', false),
  Question('The Great Wall of China is visible from space.', false),
  Question('DNA stands for "Deoxyribonucleic Acid."', true),
  Question('The capital of France is London.', false),
  Question('A kilometer is longer than a mile.', false),
  Question('The human body has four lungs.', false),
  Question('Penguins are mammals.', false),
  Question('Diamonds are made of carbon.', true),
  Question('The Pacific Ocean is the largest ocean on Earth.', true),
  Question('The moon is larger than Earth.', false),
  Question('Bananas grow on trees.', false),
  Question('Mars is known as the "Red Planet" due to its red color.', true),
  Question('The human heart pumps blood to the lungs and the brain.', true),
  Question('Lightning never strikes the same place twice.', false),
  Question('The Statue of Liberty was a gift from France to the United States.', true),
  Question('All matter is composed of atoms.', true),
  Question('The Atlantic Ocean is shrinking.', false),
  Question('Dolphins are fish.', false),
  Question('The Mona Lisa was painted by Leonardo da Vinci.', true),
  Question('The Earth\'s inner core is liquid.', false),
  Question('Sound travels faster in water than in air.', true),
  Question('Mount Everest is the tallest mountain in the world.', true),
  Question('Birds are reptiles.', false),
  Question('The chemical symbol for gold is "Au."', true),
  Question('The Nile River is the longest river in the world.', true),
  Question('The Eiffel Tower is taller in the summer due to thermal expansion.', true),
  Question('Snakes have slimy skin.', false),
  Question('Hurricanes rotate counterclockwise in the Northern Hemisphere.', true),
  Question('The Statue of Liberty faces west.', false),
  Question('The Great Barrier Reef is located in the Atlantic Ocean.', false),
  Question('Oxygen is a flammable gas.', false),
  Question('The planet closest to the Sun is Venus.', false),
  Question('Spiders are insects.', false),
  Question('The human skeleton is made up of 206 bones.', true),
  Question('The Big Bang theory explains the origin of the universe.', true),
  Question('Octopuses have three hearts.', true),
  Question('The Sahara Desert is the largest desert in the world.', true),
  Question('The Amazon River flows through Brazil.', true),
  Question('Venus is the hottest planet in our solar system.', true),
  Question('The Declaration of Independence was signed in 1776.', true),
  Question('The Earth\'s moon has a breathable atmosphere.', false),
  Question('Gold is a good conductor of electricity.', true),
  Question('Mars has two moons named Phobos and Deimos.', true),
  Question('The Great Wall of China was built in a single year.', false),
  Question('Lightning is hotter than the surface of the Sun.', true),
  Question('The human brain has five lobes.', false),
  Question('Cats are nocturnal animals.', true),
  Question('The Statue of Liberty was originally a gift from Russia.', false),
  Question('The Amazon Rainforest is located in Africa.', false),
  Question('Glass is a supercooled liquid.', false),
  Question('A day on Venus is longer than a year on Venus.', true),
  Question('The periodic table of elements has 118 elements.', true),
  Question('Honey never spoils.', true),
  Question('Astronauts in space experience "weightlessness" due to the absence of gravity.', true),
  Question('The human body can regrow lost limbs.', false),
  Question('The Statue of Liberty is made entirely of copper.', false),
  Question('A circle has three sides.', false),
  Question('Sound cannot travel through a vacuum.', true),
  Question('A leap year occurs every 4 years.', true),
  Question('The planet Neptune is closer to the Sun than Earth.', false),
  Question('The fastest land animal is the cheetah.', true),
  Question('The Great Wall of China is the only man-made structure visible from space.', false),
  Question('Kangaroos are native to South America.', false),
  Question('An octopus has three hearts.', true),
  Question('The largest organ in the human body is the liver.', false),
  Question('The Great Wall of China was built to keep out invading armies.', true),
  Question('There are 24 hours in a day on every planet.', false),
  Question('The North Pole is located at the center of the Arctic Ocean.', false),
  Question('Jellyfish are not considered fish.', true),
  Question('The Sahara Desert used to be a lush, green region.', true),
  Question('A full moon occurs every month.', true),
  Question('The speed of light is constant in a vacuum.', true),
  Question('Bats are blind.', false),
  Question('The shortest war in history lasted only 38 minutes.', true),
  Question('The human body can withstand extreme temperatures without protection.', false),
  Question('The Mona Lisa is displayed in the Louvre Museum in London.', false),
  Question('The Andes Mountains are the longest mountain range in the world.', true),
  Question('The Amazon River flows from west to east.', false),
  Question('The United States has 50 states.', true),
  Question('The largest planet in our solar system is Saturn.', false),
  Question('Antarctica is the driest continent on Earth.', true),
  Question('Light is both a particle and a wave.', true),
  Question('A diamond is the hardest naturally occurring substance on Earth.', true),
  Question('The Statue of Liberty is located in Washington, D.C.', false),
  Question('Tornadoes only occur in the United States.', false),
  Question('Gold is a rare element in the Earth\'s crust.', true),
  Question('The Earth\'s orbit around the Sun is a perfect circle.', false),
  Question('Water is a good conductor of electricity.', true),
  Question('The word "telephone" comes from Greek and means "distant sound."', true),
  Question('The human body is composed of 70% water.', true),
  Question('A tsunami is caused by underwater volcanic eruptions.', false),
  Question('The highest recorded temperature on Earth is over 200 degrees Celsius.', false),
  Question('The "Mona Lisa" was stolen and recovered multiple times.', true),
  Question('Lightning never strikes the ocean.', false),
  Question('The Great Wall of China is over 13,000 miles long.', true),
  Question('Mice love cheese.', false),
  Question('The speed of sound is faster in water than in air.', true),
  Question('The smallest planet in our solar system is Mercury.', true),
  Question('Polar bears are native to Antarctica.', false),
  Question('Tigers are the largest cats in the world.', true),
];
